### ISSUE TITLE
Why the view in helioviewer is different than in stereo.gsfc.nasa.gov

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/jp2gen#39]
Example: 
![Screenshot_1](https://user-images.githubusercontent.com/20747347/169666805-7a024201-c9ff-4895-b34f-29c582677e15.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/20747347/169666807-3a89add2-3a6c-45da-9ef8-75287dba76ae.jpg)

**Comment by wafels** [comment]
New, corrected FITS data is now available. Re-processing will occur in the next couple of days.

**Comment by dgarciabriseno** [comment]
These were re-imported a long time back. I just double checked that the image mentioned above on 2022-05-18 16:23:30 is showing up at the right angle. Closing now.
